### ISSUE TITLE
onPress of overflow touchableOpacity returns event as first parameter whereas other touchableOpacity of images return image url.

### ISSUE THREAD

**Issue by natashajaved** [jibraniqbal666/react-native-fb-image-grid#1]
overflow && (
            <TouchableOpacity
              onPress={event => onPress(event, images[start + 1])}
              style={__styles.item_view_overlay}
            >
              <Text style={__styles.text}>{`+${images.length - 5}`}</Text>
            </TouchableOpacity>)

This could be improved by sending the image as the first paramater as well, keeping the consistency , plus an addition could be made of sending index of image in parameter as well as it could be used to uniquely identify the image plus helpul if combining it with an imageSlider where index of image could be used to load the accurate image e.g if 2nd image is clicked then passing this index to slider so it can load that image (just a scenario to communicate that index could be useful). along with this catering the fact that duplicate urls may also exist.
e.g 
overflow && (
            <TouchableOpacity
              onPress={event => onPress(images[start + 1], start+1, event)}
              style={__styles.item_view_overlay}
            >
              <Text style={__styles.text}>{`+${images.length - 5}`}</Text>
            </TouchableOpacity>)

**Comment by jibraniqbal666** [comment]
thanks for the pointing out the issue, I will update when I get time, any PR would be welcoming if you wanna fix it.

**Comment by natashajaved** [comment]
My pleasure, that's what contibuting is about. And yes, i would be happy to.
