### ISSUE TITLE
Error while importing FbGrid

### ISSUE THREAD

**Issue by RusimbiP** [jibraniqbal666/react-native-fb-image-grid#14]
Hello, Thanks for this wonderful library. Two functions are not being imported from react and react-native: Component and StyleSheet
![error](https://user-images.githubusercontent.com/54870069/102017421-8fe8e080-3d6f-11eb-9c73-e62bc21648fe.png)

**Comment by RusimbiP** [comment]
![error2](https://user-images.githubusercontent.com/54870069/102017518-29b08d80-3d70-11eb-85cd-d00b32f48785.jpg)

**Comment by jibraniqbal666** [comment]
thanks for the PR, I will check it and publish the new version, can you please elaborate more about the issue as it was working before, as this library was functioning as expected.

**Comment by RusimbiP** [comment]
Thanks, When I tried to import FBGrid, I got errors in the screenshot above.

**Comment by jibraniqbal666** [comment]
I will create 0.0.5 release, as I get time.
